<?php

if (function_exists('acf_add_local_field_group')):

    acf_add_local_field_group([
        'key' => 'group_product_acf',
        'title' => 'Product Fields',
        'fields' => [
            [
                'key' => 'field_product_specialities',
                'label' => 'Specialities',
                'name' => 'specialities',
                'type' => 'select',
                'instructions' => 'Select one or more specialities',
                'required' => 0,
                'choices' => [
                    'Ortopedia' => 'Ortopedia',
                ],
                'allow_null' => 1,
                'multiple' => 1,
                'ui' => 1,
                'return_format' => 'value',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_product_brands',
                'label' => 'Brands',
                'name' => 'brands',
                'type' => 'select',
                'instructions' => 'Select one or more brands',
                'required' => 0,
                'choices' => [
                    'ACF Medical' => 'ACF Medical',
                    'Bowa Medical' => 'Bowa Medical',
                    'MDL' => 'MDL',
                    'Apex' => 'Apex',
                    'Macom' => 'Macom',
                ],
                'allow_null' => 1,
                'multiple' => 1,
                'ui' => 1,
                'return_format' => 'value',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_product_logo_brand',
                'label' => 'Logo Brand',
                'name' => 'logoBrand',
                'type' => 'image',
                'return_format' => 'array',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_product_logo_brand_second',
                'label' => 'Logo Brand Second',
                'name' => 'logoBrandSecond',
                'type' => 'image',
                'return_format' => 'array',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_product_image_url',
                'label' => 'Main Product Image',
                'name' => 'imageUrl',
                'type' => 'image',
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_product_description',
                'label' => 'Description',
                'name' => 'description',
                'type' => 'textarea',
                'rows' => 3,
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_product_subtitle',
                'label' => 'Subtitle',
                'name' => 'subtitle',
                'type' => 'text',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_product_tags',
                'label' => 'Tags',
                'name' => 'tags',
                'type' => 'select',
                'multiple' => 1,
                'ui' => 1,
                'choices' => [
                    'Joelho' => 'Joelho',
                    'Quadril' => 'Quadril',
                    'Trauma' => 'Trauma',
                    'Ombro' => 'Ombro',
                    'Cabeça e Pescoço' => 'Cabeça e Pescoço',
                    'Mão' => 'Mão',
                    'Pé' => 'Pé',
                    'Coluna' => 'Coluna',
                ],
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_product_about',
                'label' => 'About',
                'name' => 'about',
                'type' => 'repeater',
                'layout' => 'table',
                'button_label' => 'Add point',
                'sub_fields' => [
                    [
                        'key' => 'field_product_about_point',
                        'label' => 'Point',
                        'name' => 'point',
                        'type' => 'text',
                    ],
                ],
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_product_general_information',
                'label' => 'General Information',
                'name' => 'generalInformation',
                'type' => 'wysiwyg',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_product_technical_data',
                'label' => 'Technical Data',
                'name' => 'technicalData',
                'type' => 'repeater',
                'layout' => 'table',
                'button_label' => 'Add row',
                'sub_fields' => [
                    [
                        'key' => 'field_product_technical_data_col1',
                        'label' => 'Column 1',
                        'name' => 'col1',
                        'type' => 'text',
                    ],
                    [
                        'key' => 'field_product_technical_data_col2',
                        'label' => 'Column 2',
                        'name' => 'col2',
                        'type' => 'text',
                    ],
                    [
                        'key' => 'field_product_technical_data_col3',
                        'label' => 'Column 3',
                        'name' => 'col3',
                        'type' => 'text',
                    ],
                    [
                        'key' => 'field_product_technical_data_col4',
                        'label' => 'Column 4',
                        'name' => 'col4',
                        'type' => 'text',
                    ],
                ],
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_product_pictures',
                'label' => 'Pictures',
                'name' => 'pictures',
                'type' => 'gallery',
                'return_format' => 'array',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_product_links',
                'label' => 'Links/Downloads',
                'name' => 'links',
                'type' => 'repeater',
                'layout' => 'table',
                'sub_fields' => [
                    [
                        'key' => 'field_product_links_title',
                        'label' => 'Title',
                        'name' => 'title',
                        'type' => 'text',
                    ],
                    [
                        'key' => 'field_product_links_file_url',
                        'label' => 'File/URL',
                        'name' => 'fileUrl',
                        'type' => 'text',
                    ],
                    [
                        'key' => 'field_product_links_file_name',
                        'label' => 'File Name/ANVISA',
                        'name' => 'fileName',
                        'type' => 'text',
                    ],
                    [
                        'key' => 'field_product_links_type',
                        'label' => 'Type',
                        'name' => 'type',
                        'type' => 'select',
                        'choices' => [
                            'CATALOG' => 'Catalog',
                            'CASE_REPORTS' => 'Case Reports',
                            'ARTICLES' => 'Articles',
                            'DIRECTIONS_FOR_USE' => 'Directions for Use',
                            'DEFAULT' => 'Default',
                        ],
                    ],
                ],
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_product_videos',
                'label' => 'Videos',
                'name' => 'videos',
                'type' => 'repeater',
                'layout' => 'block',
                'sub_fields' => [
                    [
                        'key' => 'field_product_videos_description',
                        'label' => 'Description',
                        'name' => 'description',
                        'type' => 'textarea',
                        'rows' => 2,
                    ],
                    [
                        'key' => 'field_product_videos_url',
                        'label' => 'Video URL',
                        'name' => 'videoUrl',
                        'type' => 'text',
                    ],
                ],
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_product_images',
                'label' => 'Additional Images',
                'name' => 'images',
                'type' => 'gallery',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_product_testimonial',
                'label' => 'Testimonial',
                'name' => 'testimonial',
                'type' => 'group',
                'layout' => 'block',
                'sub_fields' => [
                    [
                        'key' => 'field_product_testimonial_text',
                        'label' => 'Testimonial Text',
                        'name' => 'testimonialText',
                        'type' => 'textarea',
                    ],
                    [
                        'key' => 'field_product_testimonial_pictures',
                        'label' => 'Testimonial Gallery',
                        'name' => 'testimonialPictures',
                        'type' => 'gallery',
                    ],
                    [
                        'key' => 'field_product_testimonial_doctor_name',
                        'label' => 'Doctor Name',
                        'name' => 'doctorName',
                        'type' => 'text',
                    ],
                    [
                        'key' => 'field_product_testimonial_doctor_specialty',
                        'label' => 'Doctor Specialty/CRM',
                        'name' => 'doctorSpecialty',
                        'type' => 'text',
                    ],
                    [
                        'key' => 'field_product_testimonial_doctor_photo',
                        'label' => 'Doctor Photo',
                        'name' => 'doctorPhoto',
                        'type' => 'image',
                    ],
                ],
                'show_in_graphql' => 1,
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'product',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_graphql' => 1,
        'graphql_field_name' => 'productacf',
    ]);

endif;
